name: CI

on:
  pull_request:
    branches: [forma11y.org]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependencies
        run: make setup
      - name: Test Website
        run: make test
